export default {
  desk: 'DeskScene',
  monitor: 'Monitor',
  monitorFace: 'MonitorFace',
  plant: 'MovablePlant',
  pot: 'MovablePot',
  mug: 'Mug',
  wall: 'Wall',
  key: 'Key',
  keyboardBase: 'KeyboardBase',
  pencil: 'Pencil',
  pencilMiddle: 'PencilMiddle',
  pencilHolder: 'PencilHolder',
  pencilEraser: 'PencilEraser',
  pencilLead: 'PencilLead',
  pencilWood: 'PencilWood',
}